# Generated by Django 6.0.6 on 2026-09-03 07:17

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Must run before the Chunk.embedding column is created, so the `vector`
        # type exists. No-ops on non-PostgreSQL backends (e.g. sqlite in CI).
        VectorExtension(),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.CharField(help_text='Path of the source file, relative to the corpus directory.', max_length=1024, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('content_hash', models.CharField(help_text='sha256 of the raw file contents; used to skip re-ingesting unchanged documents.', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['source_path'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='0-based index of this chunk within its document.')),
                ('heading_path', models.CharField(blank=True, help_text="Markdown heading trail for the chunk, e.g. 'Setup > Docker'. Shown as the citation location in answers.", max_length=1024)),
                ('content', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rag.document')),
            ],
            options={
                'ordering': ['document', 'position'],
                'constraints': [models.UniqueConstraint(fields=('document', 'position'), name='unique_chunk_position_per_document')],
            },
        ),
    ]
