# Generated by Django 6.0.6 on 2026-09-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_chunk_embedding_hnsw_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='body',
            field=models.TextField(blank=True, default='', help_text='Raw Markdown of the document (frontmatter removed), served by the corpus API.'),
        ),
    ]
